[package]
name = "github-actions-models"
description = "High-quality data models for GitHub Actions workflows, actions, and related components"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/woodruffw/github-actions-models"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"

[dev-dependencies]
